name: standard_util
description: A collection of basic standard flutter utility class.
version: 0.0.1
repository: https://github.com/fronio/standard_util

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
